#include QMK_KEYBOARD_H
#if __has_include("keymap.h")
#    include "keymap.h"
#endif


/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [0] = LAYOUT_split_3x6_3(KC_NO, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_NO, KC_NO, KC_A, KC_S, KC_D, KC_F, KC_G, KC_H, KC_J, KC_K, KC_L, KC_SCLN, KC_NO, KC_NO, KC_Z, KC_X, KC_C, KC_V, KC_B, KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, KC_NO, LT(2,KC_TAB), LT(1,KC_SPC), KC_ESC, KC_ENT, KC_BSPC, KC_QUOT),
    [1] = LAYOUT_split_3x6_3(KC_NO, KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_F6, KC_F7, KC_F8, KC_F9, KC_F10, KC_NO, KC_NO, LALT_T(KC_1), LGUI_T(KC_2), LCTL_T(KC_3), LSFT_T(KC_4), KC_5, KC_6, RSFT_T(KC_7), RCTL_T(KC_8), RGUI_T(KC_9), RALT_T(KC_0), KC_NO, KC_NO, KC_NUBS, KC_PSCR, KC_CAPS, KC_GRV, KC_APP, KC_NUHS, KC_LBRC, KC_COMM, KC_DOT, KC_RBRC, KC_NO, KC_F11, KC_TRNS, KC_F12, KC_DEL, KC_MINS, KC_EQL),
    [2] = LAYOUT_split_3x6_3(KC_NO, KC_LALT, KC_LGUI, KC_LCTL, KC_LSFT, KC_PSCR, KC_INS, KC_END, KC_HOME, KC_NO, KC_NO, KC_NO, KC_NO, KC_LALT, KC_LGUI, KC_LCTL, KC_LSFT, KC_NO, KC_LEFT, KC_DOWN, KC_UP, KC_RGHT, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_PGUP, KC_PGDN, KC_NO, KC_PAUS, KC_PGDN, KC_PGUP, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO)
};



#ifdef OTHER_KEYMAP_C
#    include OTHER_KEYMAP_C
#endif // OTHER_KEYMAP_C

